yolo_model:

  config_file:
    name: yolov3-voc_last.cfg
  weight_file:
    name: yolov3_gomi.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - pet
      - can
      - bento